# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [ ]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

In [34]:
import numpy as np
import datetime as date

In [35]:
arrayNunpy =  np.arange(0, 1000000, 1)
arrayList = list(range(0,1000000,1))


## fazendo os calculos com Array Numpy

In [36]:
arrayNunpy

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [38]:
date_inicio = date.datetime.now() 

arrayNunpy = arrayNunpy * 2
date_termino = date.datetime.now() 

utilizandoNumpy = (date_termino-date_inicio)


date_inicio = date.datetime.now() 

arrayList = arrayList * 2
date_termino = date.datetime.now() 

utilizandoListPython  =(date_termino-date_inicio)

print(utilizandoNumpy,utilizandoListPython )

0:00:00.003987 0:00:00.060839


In [6]:
date_inicio = date.datetime.now() 

arrayList * 2
date_termino = date.datetime.now() 

print(date_termino-date_inicio)

0:00:00.036899


In [13]:
arrayNunpy

array([     0,      1,      2, ..., 999997, 999998, 999999])

### Exercício 2

In [ ]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

In [39]:
variavel = np.arange(10)
variavel



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
 variavel[5:8] = 0

 variavel

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

### Exercício 3

In [55]:
# Crie um array de 3 dimensões e imprima a dimensão 1 


matriz = np.array([[1,2,3],[4,5,6],[4,5,6]]) 
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [56]:
matriz.shape

(3, 3)

### Exercício 4

In [ ]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

In [41]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
matriz[2]

array([7, 8, 9])

In [42]:
matriz[1][1:3]


array([5, 6])

### Exercício 5

In [11]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## para calcular a tranposta em numpy basta colocar essa propriedade

In [43]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [16]:
arr[0]  

array([0, 1, 2, 3, 4])

### Exercício 6

In [45]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [46]:

indice = 0
for condicao in cond:
    if(condicao == True):
        print(xarr[indice])
    else:
        print(yarr[indice])
    indice +=1

1.1
2.2
1.3
1.4
2.5


In [47]:
for x, y, c in zip(xarr, yarr, cond):
    print(x, y, c)

1.1 2.1 True
1.2 2.2 False
1.3 2.3 True
1.4 2.4 True
1.5 2.5 False


### Exercício 7

In [ ]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B

In [50]:
A = np.arange(10)
print(A)
np.save('array_a', A)

[0 1 2 3 4 5 6 7 8 9]


In [51]:
B = np.load('array_a.npy')
print(B)

[0 1 2 3 4 5 6 7 8 9]


In [65]:
import os 



### Exercício 8

In [53]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])


uniques  = obj.unique()

uniques

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [60]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

data  = resp.json()
data[0]['title']


'Indexing change with integer slices not in changelog?'

In [61]:
dataframe = pd.DataFrame(data,columns=["number","title","labels","state"])
dataframe

number                                              title  \
0    31469  Indexing change with integer slices not in cha...   
1    31468                     REF: use inherit_names for DTI   
2    31467  pd.ExcelFile closes stream on destruction in p...   
3    31466  pandas.apply() converts all columns to object ...   
4    31465                       Issue pyodbc and to_sql HIVE   
5    31464  read_json with typ="series" of json list of bo...   
6    31463  Regression: objToJSON "nonvoid function does n...   
7    31462                                 Some code cleanups   
8    31461                  DOC: Fix DataFrame.to_csv example   
9    31460  DOC: Example of DataFrame.to_csv() is not show...   
10   31459  ENH: pd.cut should be able to return a Series ...   
11   31458  Fix to_csv and to_excel links on read_csv, rea...   
12   31457  Timedelta multiplication crashes for large arrays   
13   31456  BUG: Groupby.apply wasn't allowing for functio...   
14   31455  jobs failling with error raise RuntimeError("C...   
15   31453  pandas._testing.assert_produces_warning docstr...   
16   31452  Series .attrs is not correctly maintained/prop...   
17   31451  DOC: Fixed example section in pandas/core/dtyp...   
18   31450  REGR: groupby().agg fails on categorical colum...   
19   31449  REGR: Assignment to MultiIndex fails for panda...   
20   31448  DOC: to_csv is not properly linked from read_c...   
21   31447              REGR: to_csv(na_rep) truncates values   
22   31446  REGR: Array.__setitem__ failing with nullable ...   
23   31444  Enhancement: code sugar for index.get_level_va...   
24   31441       TypeError: copy() takes no keyword arguments   
25   31440                BUG: Fix qcut for nullable integers   
26   31437     BUG: PeriodIndex.is_monotonic with leading NaT   
27   31435  ENH: Added index to testing assert message whe...   
28   31433             REF: use inherit_names for PeriodIndex   
29   31427          REF: use inherit_names for TimedeltaIndex   

                                               labels state  
0   [{'id': 32815646, 'node_id': 'MDU6TGFiZWwzMjgx...  open  
1                                                  []  open  
2   [{'id': 32815646, 'node_id': 'MDU6TGFiZWwzMjgx...  open  
3                                                  []  open  
4                                                  []  open  
5                                                  []  open  
6                                                  []  open  
7   [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
8   [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
9   [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
10                                                 []  open  
11                                                 []  open  
12                                                 []  open  
13                                                 []  open  
14  [{'id': 307649777, 'node_id': 'MDU6TGFiZWwzMDc...  open  
15                                                 []  open  
16  [{'id': 1539579994, 'node_id': 'MDU6TGFiZWwxNT...  open  
17                                                 []  open  
18  [{'id': 78527356, 'node_id': 'MDU6TGFiZWw3ODUy...  open  
19  [{'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyM...  open  
20  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
21  [{'id': 47229171, 'node_id': 'MDU6TGFiZWw0NzIy...  open  
22  [{'id': 1817503692, 'node_id': 'MDU6TGFiZWwxOD...  open  
23                                                 []  open  
24  [{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...  open  
25                                                 []  open  
26  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
27                                                 []  open  
28                                                 []  open  
29                                                 []  open

number                                              title  \
0    20975  Slicing columns with mixed types <str>,<int> f...   
1    20974  BUG: Fix drop_duplicates failure when DataFram...   
2    20970            performance when "combining" categories   
3    20969        Getting a ... in my CSV when using to_csv()   
4    20968                         Sharey keyword for boxplot   
5    20967   Column can be extended beyond DataFrame's length   
6    20966             BUG: Fix wrong khash method definition   
7    20965  BUG: Fix combine_first converts other columns ...   
8    20964  BUG: Index with integer data and datetime64[ns...   
9    20962  df.rank() has different behavior for python2 a...   
10   20960  DOC: add reshaping visuals to the docs (Reshap...   
11   20958  Using apply on a grouper works only if done af...   
12   20956  ENH: Return DatetimeIndex or TimedeltaIndex bi...   
13   20955  Building documentation fails with `ImportError...   
14   20954  Correlation inconsistencies between Series and...   
15   20951  Addressing multiindex raises TypeError if indi...   
16   20948  Indexing DataFrame with DateOffset is nearly i...   
17   20947        Allow drop bins when using the cut function   
18   20945  Data is mismatched with labels after stack wit...   
19   20944                       Drop rows based on condition   
20   20943  pd.read_sql does not handle queries that retur...   
21   20940                       unclear error with  read_sas   
22   20937  BUG: Series(DTI/TDI) loses the frequency infor...   
23   20936  __new__() missing 1 required positional argume...   
24   20932  API: expose `axis` keyword in pandas.core.algo...   
25   20930  DOC: Index.get_loc Cannot Accept List-like Tol...   
26   20928             Added script to fetch wheels [ci skip]   
27   20927  read_sas OverflowError: int too big to convert...   
28   20926   BLD: Lint for invalid files in wheels / packages   
29   20925  Series.reset_index(level_name, drop=True) acce...   

                                               labels state  
0                                                  []  open  
1   [{'id': 76811, 'url': 'https://api.github.com/...  open  
2   [{'id': 78527356, 'url': 'https://api.github.c...  open  
3                                                  []  open  
4                                                  []  open  
5                                                  []  open  
6   [{'id': 76811, 'url': 'https://api.github.com/...  open  
7   [{'id': 76811, 'url': 'https://api.github.com/...  open  
8                                                  []  open  
9                                                  []  open  
10  [{'id': 134699, 'url': 'https://api.github.com...  open  
11  [{'id': 76811, 'url': 'https://api.github.com/...  open  
12  [{'id': 49597148, 'url': 'https://api.github.c...  open  
13                                                 []  open  
14                                                 []  open  
15                                                 []  open  
16                                                 []  open  
17  [{'id': 76812, 'url': 'https://api.github.com/...  open  
18                                                 []  open  
19                                                 []  open  
20                                                 []  open  
21                                                 []  open  
22                                                 []  open  
23                                                 []  open  
24  [{'id': 35818298, 'url': 'https://api.github.c...  open  
25                                                 []  open  
26  [{'id': 131473665, 'url': 'https://api.github....  open  
27                                                 []  open  
28  [{'id': 129350, 'url': 'https://api.github.com...  open  
29  [{'id': 42670965, 'url': 'https://api.github.c...  open

### Exercício 10

In [ ]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>